# Generated by Django 5.2.1 on 2025-06-28 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Service categories',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('stat_1_percent', models.CharField(max_length=25)),
                ('stat_1_text', models.CharField(max_length=255)),
                ('brand_1', models.CharField(max_length=125)),
                ('stat_2_percent', models.CharField(max_length=25)),
                ('stat_2_text', models.CharField(max_length=255)),
                ('brand_2', models.CharField(max_length=125)),
                ('image', models.ImageField(upload_to='story/')),
                ('service_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.servicecategory')),
            ],
        ),
    ]
