# Generated by Django 5.2.1 on 2025-06-28 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemoSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('work_email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=200)),
                ('company_size', models.CharField(max_length=100)),
                ('num_people_to_train', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=100)),
                ('job_level', models.CharField(max_length=100)),
                ('training_needs', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
