# Generated by Django 5.2.1 on 2025-07-07 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_course_reviews'),
        ('courses', '0006_auto_20250707_1101'),
    ]

    operations = [
    ]
