# Generated by Django 5.2.1 on 2025-06-28 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('initials', models.CharField(max_length=2)),
                ('rating', models.ImageField(upload_to='reviews/')),
                ('time_ago', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('stat_1_percent', models.CharField(max_length=25)),
                ('stat_1_text', models.CharField(max_length=255)),
                ('stat_2_percent', models.CharField(max_length=25)),
                ('stat_2_text', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='story/')),
                ('description', models.TextField()),
                ('company_icon', models.ImageField(upload_to='story/icons/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Stories',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('profile', models.ImageField(upload_to='testimonial/')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='courses.subcategory')),
            ],
        ),
    ]
