# Generated by Django 5.2.1 on 2025-07-07 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='rating_point',
            field=models.CharField(blank=True, help_text='Course rating points', max_length=25, null=True),
        ),
    ]
