# Generated by Django 5.2.1 on 2025-07-07 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_rating_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='reviews',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Course reviews'),
        ),
    ]
