# Generated by Django 5.2.1 on 2025-07-07 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='rating_point',
            field=models.CharField(max_length=25, blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='reviews',
            field=models.CharField(max_length=25, blank=True, null=True),
        ),
    ]
